New zfsinstall from mfsBSD 9.2.

diff --git a/zfsinstall b/zfsinstall
--- a/zfsinstall
+++ b/zfsinstall
@@ -2,7 +2,7 @@
 # $Id$
 #
 # mfsBSD ZFS install script
-# Copyright (c) 2011 Martin Matuska <mm at FreeBSD.org>
+# Copyright (c) 2011-2013 Martin Matuska <mm at FreeBSD.org>
 #
 # - Adapted to use zfs layout from
 #   https://wiki.freebsd.org/RootOnZFS/GPTZFSBoot/9.0-RELEASE
@@ -12,15 +12,14 @@
 #   [fschulze (Florian Schulze <florian.schulze at gmx.net>)
 
 usage() {
-	echo "Usage: $0 [-h] -d geom_provider [-d geom_provider ...] -t archive_file [-r mirror|raidz] [-m mount_point] [-p zfs_pool_name] [-V zfs_pool_version] [-s swap_partition_size] [-z zfs_partition_size] [-c] [-l] [-4]"
+	echo "Usage: $0 [-h] -d geom_provider [-d geom_provider ...] -u dist_url [-r mirror|raidz] [-m mount_point] [-p zfs_pool_name] [-V zfs_pool_version] [-s swap_partition_size] [-z zfs_partition_size] [-c] [-l] [-4]"
 }
 
 help() {
 	echo; echo "Install FreeBSD using ZFS from a compressed archive"
 	echo; echo "Required flags:"
 	echo "-d geom_provider  : geom provider(s) to install to (e.g. da0)"
-	echo "-t archive_file   : tar archive file containing the FreeBSD distribution"
-	echo "			  supported compression formats are: gzip, bzip2, xz"
+	echo "-u dist_url       : URL or directory with base.txz and kernel.txz"
 	echo; echo "Optional flags:"
 	echo "-r raidz|mirror   : select raid mode if more than one -d provider given"
 	echo "-s swap_part_size : create a swap partition with given size (default: no swap)"
@@ -30,18 +29,19 @@ help() {
 	echo "-m mount_point    : use this mount point for operations (default: /mnt)"
 	echo; echo "Examples:"
 	echo "Install on a single drive with 2GB swap:"
-	echo "$0 -d ad4 -s 2G"
+	echo "$0 -u /path/to/release -d da0 -s 2G"
 	echo "Install on a mirror without swap, pool name rpool:"
-	echo "$0 -d ad4 -d ad6 -r mirror -p rpool"
+	echo "$0 -u /path/to/release -d da0 -d da1 -r mirror -p rpool"
 	echo; echo "Notes:"
 	echo "When using swap and raidz/mirror, the swap partition is created on all drives."
 	echo "The /etc/fstab entry will contatin only the first drive's swap partition."
 	echo "You can enable all swap partitions and/or make a gmirror-ed swap later."
 }
 
-while getopts d:t:r:p:s:z:m:V:hcl4 o; do
+while getopts d:u:t:r:p:s:z:m:V:hcl4 o; do
 	case "$o" in
 		d) DEVS="$DEVS ${OPTARG##/dev/}" ;;
+		u) URL="${OPTARG}" ;;
 		t) ARCHIVE="${OPTARG}" ;;
 		p) POOL="${OPTARG}" ;;
 		s) SWAP="${OPTARG}" ;;
@@ -68,7 +68,7 @@ elif [ "$ZFS_VERSION" -lt "13" ]; then
 	exit 1
 fi
 
-if [ -z "$DEVS" -o -z "$ARCHIVE" ]; then
+if [ -z "$DEVS" -o -z "$URL" -a -z "$ARCHIVE" ]; then
 	usage
 	exit 1
 fi
@@ -137,28 +137,25 @@ for DEV in ${DEVS}; do
 	fi
 done
 
-if ! [ -f "${ARCHIVE}" ]; then
-	echo "Error: file $ARCHIVE does not exist"
-	exit 1
-fi
-
-DIRECT_TAR=0
-FTYPE=`/usr/bin/file -b --mime-type ${ARCHIVE}`
-if [ "$FTYPE" = "application/x-tar" ]; then
-	DIRECT_TAR=1
-elif [ "$FTYPE" = "application/x-gzip" ]; then
-	EXTRACT_CMD=/usr/bin/gzip
-elif [ "$FTYPE" = "application/x-bzip2" ]; then
-	EXTRACT_CMD=/usr/bin/bzip2
-elif [ "$FTYPE" = "application/x-xz" ]; then
-	if [ ! -x "`/usr/bin/which xz`" ]; then
-		echo "xz-compressed file selcted and xz is not installed";
+if [ -z "${URL}" ]; then
+	if ! [ -f "${ARCHIVE}" ]; then
+		echo "Error: file $ARCHIVE does not exist"
 		exit 1
+	else
+		EXTRACT_FILES=${ARCHIVE}
 	fi
-	EXTRACT_CMD=`which xz`
 else
-	echo "Archive must be uncompressed or gzip, bzip2 or xz compressed"
-	exit 1
+	if [ -d "${URL}" ]; then
+		for file in base.txz kernel.txz; do
+			if ! [ -f "${URL}/${file}" ]; then
+				echo "File not found: ${URL}/${file}"
+				exit 1
+			fi
+		done
+		EXTRACT_FILES="${URL}/base.txz ${URL}/kernel.txz"
+	else
+		EXTRACT_FILES="/tmp/base.txz /tmp/kernel.txz"
+	fi
 fi
 
 if [ -z "$MNT" ]; then
@@ -175,6 +172,18 @@ if [ -n "${ZPART}" ]; then
 fi
 
 ALTROOT="-o altroot=${MNT} -o cachefile=/boot/zfs/zpool.cache"
+
+# Fetch base.txz and kernel.txz
+
+if [ -n "${URL}" -a ! -d "${URL}" ]; then
+	if ! /usr/bin/fetch -o /tmp/base.txz "${URL}/base.txz"; then
+		echo "Error fetching ${URL}/base.txz"
+		exit 1
+	elif ! /usr/bin/fetch -o /tmp/kernel.txz "${URL}/kernel.txz"; then
+		echo "Error fetching ${URL}/kernel.txz"
+		exit 1
+	fi
+fi
 
 # Create GPT
 
@@ -353,17 +362,12 @@ echo " done"
 /sbin/zfs list -r ${POOL}
 
 echo -n "Extracting FreeBSD distribution ..."
-if [ "${DIRECT_TAR}" = "1" ]; then
-	if ! /usr/bin/tar -C ${MNT} -x -f ${ARCHIVE} > /dev/null 2> /dev/null; then
+for file in ${EXTRACT_FILES}; do
+	if ! /usr/bin/tar -C ${MNT} -x -f ${file} > /dev/null 2> /dev/null; then
 		echo " error"
 		exit 1
 	fi
-else
-	if ! ${EXTRACT_CMD} -d -c ${ARCHIVE} | /usr/bin/tar -C ${MNT} -x -f - > /dev/null 2> /dev/null; then
-		echo " error"
-		exit 1
-	fi
-fi
+done
 echo " done"
 
 # Adjust configuration files
@@ -399,12 +403,6 @@ if ! /bin/cp /boot/zfs/zpool.cache ${MNT}/boot/zfs/ > /dev/null 2> /dev/null; th
 fi
 echo " done"
 
-# Mount devfs for post-configuration
-
-if ! /sbin/mount -t devfs devfs ${MNT}/dev; then
-	echo "Error mounting devfs on ${MNT}/dev"
-fi
-
 echo -n "Setting ${POOL}/var/empty to read only ..."
 if ! /sbin/zfs set readonly=on ${POOL}/var/empty > /dev/null 2> /dev/null; then
 	echo " error"
@@ -416,8 +414,10 @@ echo ""
 echo "Installation complete."
 echo "The system will boot from ZFS with clean install on next reboot"
 echo ""
-echo "You may type \"chroot ${MNT}\" and make any adjustments you need."
-echo "For example, change the root password or edit/create /etc/rc.conf for"
-echo "for system services. "
+echo "You may make adjustments to the installed system using chroot:" 
+echo "chroot ${MNT}"
+echo ""
+echo "Some adjustments may require a mounted devfs:"
+echo "mount -t devfs devfs ${MNT}/dev"
 echo ""
 echo "WARNING - Don't export ZFS pool \"${POOL}\"!"
